blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://github.com/pgpvieira-code/vvault/issues
    about: Ask questions and discuss ideas with the community on Discord
  - name: 📖 Documentation
    url: https://docs.aliasvault.com
    about: Check out the official (self-host) documentation